### ISSUE TITLE
License

### ISSUE THREAD

**Issue by urbste** [CenekAlbl/RnP#3]
Hi Cenek,

thank your for open sourcing your solvers!
Could you tell me what the license is for your code? 
I would potentially like to include them in our fork of TheiaSfM which has a BSD license.

Cheers
Steffen

**Comment by CenekAlbl** [comment]
Hi Steffen,

thanks for reaching out, I would love to see the solvers implemented in an open-source SfM library such as Theia! Let me know if I can help.

I haven't thought of the license yet, but I think BSD is fine.

Cheers,

Cenek

**Comment by urbste** [comment]
Cool, that's great!

I just saw that you are using two files that have a GPL header: sturm.cc and hidden6.h

I am not that familiar with the math behind it. The function is called: **find_real_roots_sturm**
There are some root finding functions in Theia. Could one replace the sturm function with the jenkins-traub algorithm? https://github.com/sweeneychris/TheiaSfM/blob/master/src/theia/math/

However I also see that this function is only used for the r6p_1lin solver. So maybe I will stick to the other ones that need initialization first.

**Comment by CenekAlbl** [comment]
You are right! At a first glance, it seems that Jenkins-Traub algorithm could serve as a replacement. Not sure about the speed, but this should not be critical in an SfM application. 

Yes, it is only used for R6P1Lin - for performance purposes, we had a different version with standard eigenvalue computation but that was much slower.

The performance of the other algorithms should be comparable given a good initialization of P3P so that should be a good starting point.

Is TheiaSfM still being actively developed?

**Comment by urbste** [comment]
Ok, then I will have a look at the Jenkins-Traub algorithm.

We are using TheiaSfM quite a lot, as it is great toolbox for geometric vision and SfM with a good performance. We are currently also developing Python Bindings to it, that we plan on releasing to the public as well.
